# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-28 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nhlplayoff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayoffRound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_name', models.CharField(max_length=100)),
                ('round_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayoffSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nhlplayoff.League')),
                ('teams', models.ManyToManyField(blank=True, to='nhlplayoff.Team')),
            ],
        ),
        migrations.CreateModel(
            name='SeriesActual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1_wins', models.IntegerField()),
                ('team2_wins', models.IntegerField()),
                ('child_series', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='nhlplayoff.SeriesActual')),
                ('playoff_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nhlplayoff.PlayoffRound')),
                ('team1', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='nhlplayoff.Team')),
                ('team2', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='nhlplayoff.Team')),
            ],
        ),
        migrations.AddField(
            model_name='playoffround',
            name='playoff_season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nhlplayoff.PlayoffSeason'),
        ),
    ]
